version: '3.8'
services:
  mysql:
    image: mysql:8.0.35
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: aws-test
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - '3307:3306'
    restart: always

  springboot-app:
    image: myapp
    container_name: myapp-container
    depends_on:
      - mysql
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/aws_test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    restart: always

volumes:
  # Named Volume 컨테이너 내부 파일 시스템과 마운트 될 볼륨 위치를 알아서 잡아줌
  sparta_tigers_mysql_volume:
  sparta_tigers_redis_volume:
