# Actions 이름
# github 페이지에서 볼 수 있다.
name: Run Test

# Event Trigger.
# 특정 액션 (pull, PR 등)이 명시한 Branch에서 일어나면 동작을 수행한다.
on:
  push:
    # 배열로 여러 브랜치 지정 가능
    branches: [dev, feat/*]
  pull_request:
    branches:
      # - 로 여러 브랜치 명시 가능
      - develop

  # 실제 어떤 작업을 실행할 지에 대한 명시
  jobs:
    build:
      # 스크립트 실행 환경 (OS)
      # 배열로 선언 시 개수만큼 반복 실행
      runs-on: [ubuntu-latest]

    steps:
      - name: checkout
        # github actions 에서 재공하는 플러그인 실행 (여기서는 git checkout)
        uses: actions/checkout@v4

      - name: java setup
        uses: actions/setup-java@2
        with:
          distribution: 'adopt'
          java-version: '21'

      # gradle 실행 권한 추가
      - name: make executable gradlew
        run: chmod +x ./gradlew

      - name: run unittest
        run: |
          ./gradlew clean test
