# Actions 이름
# github 페이지에서 볼 수 있다.
name: Run Test

# Event Trigger.
# 특정 액션 (pull, PR 등)이 명시한 Branch에서 일어나면 동작을 수행한다.
on:
  push:
    # 배열로 여러 브랜치 지정 가능
    branches: [dev, feat/*]
  pull_request:
    branches:
      # - 로 여러 브랜치 명시 가능
      - develop

  # 실제 어떤 작업을 실행할 지에 대한 명시
jobs:
  build:
      # 스크립트 실행 환경 (OS)
      # 배열로 선언 시 개수만큼 반복 실행
      runs-on: [ubuntu-latest]

      services:
        mysql:
          image: mysql:8.0
          ports:
            - 3306:3306

          env:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: testdb
            MYSQL_USER: testuser
            MYSQL_PASSWORD: testpass
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

      env:
        database_local_url: mysql:3306/testdb
        database_local_username: testuser
        database_local_password: testpass

      steps:
        - name: Wait for MySQL
          run: |
              for i in {1..30}; do
                nc -z mysql 3306 && echo "MySQL is up" && break
                echo "Waiting for MySQL..."
                sleep 2
              done

        - name: checkout
          # github actions 에서 재공하는 플러그인 실행 (여기서는 git checkout)
          uses: actions/checkout@v4

        - name: java setup
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '21'

        # gradle 실행 권한 추가
        - name: make executable gradlew
          run: chmod +x ./gradlew

        - name: run unittest
          run: |
            ./gradlew clean test